#!/bin/bash
# Helper script to regenerate haskell-ci.yml with correct triggers and concurrency
# This script:
# 1. Runs haskell-ci regenerate to get the latest matrix configuration
# 2. Post-processes the generated file to add branch filters and concurrency

set -e

echo "Regenerating haskell-ci.yml with correct triggers..."

# Check if haskell-ci is available
if ! command -v haskell-ci &> /dev/null; then
    echo "Error: haskell-ci not found. Please install it first:"
    echo "  cabal install haskell-ci"
    exit 1
fi

# Backup current file
if [ -f ".github/workflows/haskell-ci.yml" ]; then
    cp .github/workflows/haskell-ci.yml .github/workflows/haskell-ci.yml.backup
    echo "Backed up current haskell-ci.yml"
fi

# Regenerate the workflow
echo "Running haskell-ci regenerate..."
haskell-ci regenerate

# Post-process the generated file to add correct triggers and concurrency
echo "Post-processing generated workflow..."

# Create a temporary file with the corrected content
cat > .github/workflows/haskell-ci.yml.tmp << 'EOF'
# This GitHub workflow config has been generated by a script via
#
#   haskell-ci 'github' 'cabal.project' '--config=cabal.haskell-ci'
#
# To regenerate the script (for example after adjusting tested-with) run
#
#   haskell-ci regenerate
#
# For more information, see https://github.com/haskell-CI/haskell-ci
#
# version: 0.19.20250531
#
# REGENDATA ("0.19.20250531",["github","cabal.project","--config=cabal.haskell-ci"])
#
name: Haskell-CI
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
EOF

# Extract the jobs section from the generated file (skip the header and on: section)
tail -n +25 .github/workflows/haskell-ci.yml >> .github/workflows/haskell-ci.yml.tmp

# Replace the original with the corrected version
mv .github/workflows/haskell-ci.yml.tmp .github/workflows/haskell-ci.yml

echo "✅ Successfully regenerated haskell-ci.yml with correct triggers:"
echo "   - push: only on main branch"
echo "   - pull_request: all events"
echo "   - concurrency: enabled to cancel in-progress runs"
echo ""
echo "The workflow will now avoid duplicate CI runs on PR updates."
