name: test-gibbon
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - review_requested
      - ready_for_review
jobs:
  linux:
    name: test-gibbon
    runs-on: ubuntu-18.04
    steps:
      - name: dependencies
        run: |
          sudo apt-get update
          sudo apt-add-repository -y 'ppa:hvr/ghc'
          sudo apt-get update
          sudo add-apt-repository -y 'ppa:plt/racket'
          sudo apt-get update
          sudo apt-get install -y libgc-dev libgmp-dev uthash-dev gcc-7 ghc-9.0.1 racket
          sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
      - name: versions
        run: |
          ghc --version
          racket --version
          gcc --version
          stack --version
          cabal --version
      - name: checkout
        uses: actions/checkout@v2
      - run: cabal v2-update -w /opt/ghc/9.0.1/bin/ghc
      - run: cabal v2-freeze -w /opt/ghc/9.0.1/bin/ghc
      - name: cache-cabal
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-cabal-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-cabal-
          path: |
            ~/.cabal/store
            ~/.cabal/packages
            dist-newstyle
      - name: build
        run: |
          cd gibbon-compiler
          cabal v2-update -w /opt/ghc/9.0.1/bin/ghc
          cabal v2-build -w /opt/ghc/9.0.1/bin/ghc .
      - name: cache-answers
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-answers
          path: gibbon-compiler/examples/build_tmp/*.ans
      - name: answers
        run: |
          cd gibbon-compiler
          make answers
      - name: list-answers
        run: |
          ls gibbon-compiler/examples/build_tmp/*.ans
      - name: tests
        run: |
          export GIBBONDIR=`pwd`
          cd gibbon-compiler/
          cabal v2-exec -w /opt/ghc/9.0.1/bin/ghc test-gibbon-examples -- -v2
